name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [lts/erbium, lts/fermium, lts/gallium]


    steps:
      - uses: actions/checkout@v2
      - name: Setpu Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install npm dependencies
        run : npm ci
      - name: Build
        run: npm run build